In [12]:
import board
import game
import math
import numpy as np
import tt

In [13]:
import board

a = board.Board(5)
a.condition = 5


a.change_state(2,0,1)
a.change_state(2,1,1)
a.change_state(2,2,1)
a.change_state(2,3,1)
a.change_state(2,4,1)

a.display()


print(a.check_win_from(2, 2, 1))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
True


In [14]:
import board

a = board.Board(5)
a.condition = 5

a.change_state(0,0,1)
a.change_state(1,1,1)
a.change_state(2,2,1)
a.change_state(3,3,1)
a.change_state(4,4,1)

a.display()

print(a.check_win_from(2, 2, 1)) 

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
True


In [15]:
import board

a = board.Board(5)
a.condition = 5 

a.change_state(0,3,1)
a.change_state(1,3,1)
a.change_state(2,3,1)
a.change_state(3,3,1)
a.change_state(4,3,1)

a.display()

print(a.check_win_from(2, 3, 1))

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]
True


In [16]:
import board
from minimax import best_move

a = board.Board(5)
a.condition = 5 


a.change_state(0,0,1)
a.change_state(1,1,1)
a.change_state(2,2,1)
a.change_state(3,3,1)


a.change_state(0,4,2)
a.change_state(1,4,2)
a.change_state(4,0,2)

a.display()

mv = best_move(a, 1)
print("best_move=", mv)

[[1 0 0 0 2]
 [0 1 0 0 2]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [2 0 0 0 0]]
best_move= (4, 4)
